name: PDS20
channels:
  - defaults
dependencies:
  - click=7.1.1
  - jupyter=1.0.0
  - matplotlib=3.1.3
  - numpy=1.18.1
  - pandas=1.0.3
  - pip=20.0.2
  - seaborn=0.10.0
  - setuptools=46.1.1
  - tensorflow=2.0.0
  - pip:
    - folium==0.10.1
